version: '3'

services:
    postgres:
        image: postgres:13.2-alpine
        restart: always
        ports:
            - "5432:5432"
        volumes: 
            - postgres-data:/var/lib/postgresql/data/
            - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
        environment: 
            POSTGRES_USER: demo_user
            POSTGRES_PASSWORD: demo_password
            POSTGRES_DB: demo_app
    
    pgadmin:
        image: dpage/pgadmin4:5.4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@test.com
            PGADMIN_DEFAULT_PASSWORD: secret
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "8080:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - "postgres"


volumes:
    postgres-data:
    pgadmin-data:
